### ISSUE TITLE
OAEP Padding with SHA-256 Digest

### ISSUE THREAD

**Issue by jeanpaul-mokaza** [soyersoyer/SwCrypt#56]
Hello, I'm trying to encrypt a string with the RSA algorithm `RSA/ECB/OAEPWithSHA-256AndMGF1Padding`.

The Java code to decrypt is as follows, which is done on server:
```
String rsaKeyAlgorithm = "RSA";
String rsaEncryptAlgorithm = "RSA/ECB/OAEPWithSHA-256AndMGF1Padding";

PrivateKey privateKey = (RSAPrivateKey) KeyFactory.getInstance(rsaKeyAlgorithm).generatePrivate(new PKCS8EncodedKeySpec(Base64.getDecoder().decode(rsaPrivateKey)));

byte[] bytes = Base64.getDecoder().decode(cipherText);

Cipher decriptCipher = Cipher.getInstance(rsaEncryptAlgorithm);
decriptCipher.init(Cipher.DECRYPT_MODE, privateKey);
return new String(decriptCipher.doFinal(bytes), charset);
```

I tried using the following function:
`try CC.RSA.encrypt(data, derKey: publicKey, tag: tag, padding: .oaep, digest: .sha256)`
But server caught the following exception:
```
Exception in thread "main" javax.crypto.BadPaddingException: Decryption error
	at java.base/sun.security.rsa.RSAPadding.unpadOAEP(RSAPadding.java:497)
	at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:292)
	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366)
	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
```

I tried to encrypt with digest `.sha1`, and decrypt on server using RSA algorithm `RSA/ECB/OAEPWithSHA-1AndMGF1Padding` and it worked fine. The issue seems to be related with `SHA-256`.

Can anyone help, please?

**Comment by jeanpaul-mokaza** [comment]
Okay nevermind, I fixed the issue. Turns out, I had to add the `OAEPParameterSpec` when decrypting in Java, as follows.

```
OAEPParameterSpec oaepParams = new OAEPParameterSpec("SHA-256", "MGF1", new MGF1ParameterSpec("SHA-256"), PSource.PSpecified.DEFAULT);
		decriptCipher.init(Cipher.DECRYPT_MODE, privateKey, oaepParams);
```
